name: Update Version on Release

on:
  repository_dispatch:
    types: [cli-release]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update Version References
        run: |
          VERSION=${{ github.event.client_payload.version }}
          sed -i "s/@v[0-9]\+\.[0-9]\+\.[0-9]\+/@v${VERSION}/g" src/app/page.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add src/app/page.js
          git commit -m "chore: update CLI version to ${{ github.event.client_payload.version }}"
          git push
